configuration.profiles=web/desktop/chrome
configuration.suites=training
configuration.environments=saucedemo_Slava
engine.composite-paths=steps/*.steps
#known-issue-provider.detect-potentially-known-issues=true
#known-issue-provider.fileName=known-issues.json
