# This environment config file is set up to host any potential high level environment properties
web-application.main-page-url=https://www.saucedemo.com/
variables.swagGoodUserName=standard_user
variables.swagLockedUserName=locked_out_user
variables.swagBrokenUserName=problem_user
variables.swagSlowUserName=performance_glitch_user
variables.swagPassword=secret_sauce
#variables.baselineAction=ESTABLISH
#variables.baselineAction=COMPARE_AGAINST
